version: '3.8'

services:
  java-maven-app:
    image: arman04/java-maven-app:1.1.2-2
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: my-pwd
